import * as crypto from 'crypto';
import * as vscode from 'vscode';

/**
 * Generates a cryptographically secure random nonce for use in webview Content Security Policy.
 * Uses 16 bytes of cryptographic randomness encoded as a hex string (32 characters).
 */
export function getNonce(): string {
	return crypto.randomBytes(16).toString('hex');
}

/**
 * Builds the Content-Security-Policy <meta> tag for a standard VS Code webview.
 *
 * The policy:
 * - Blocks all sources by default (`default-src 'none'`)
 * - Allows images and fonts from the extension's webview origin, HTTPS, and data URIs
 * - Allows inline styles and styles from the extension's webview origin
 * - Restricts scripts to those carrying the per-request nonce
 *
 * @param webview - The VS Code Webview instance (provides `cspSource` for the extension origin)
 * @param nonce   - A per-request nonce generated by {@link getNonce}
 * @returns A full `<meta http-equiv="Content-Security-Policy" ...>` HTML element string
 */
export function buildCspMeta(webview: vscode.Webview, nonce: string): string {
	const csp = [
		`default-src 'none'`,
		`img-src ${webview.cspSource} https: data:`,
		`style-src 'unsafe-inline' ${webview.cspSource}`,
		`font-src ${webview.cspSource} https: data:`,
		`script-src 'nonce-${nonce}'`,
	].join('; ');
	return `<meta http-equiv="Content-Security-Policy" content="${csp}" />`;
}
