import * as crypto from 'crypto';
import * as vscode from 'vscode';

/**
 * Generates a cryptographically secure random nonce for use in webview Content Security Policy.
 * Uses 16 bytes of cryptographic randomness encoded as a hex string (32 characters).
 */
export function getNonce(): string {
	return crypto.randomBytes(16).toString('hex');
}

/**
 * Builds the Content-Security-Policy <meta> tag for a standard VS Code webview.
 *
 * The policy:
 * - Blocks all sources by default (`default-src 'none'`)
 * - Allows images and fonts from the extension's webview origin, HTTPS, and data URIs
 * - Allows inline styles and styles from the extension's webview origin
 * - Restricts scripts to those carrying the per-request nonce
 *
 * @param webview - The VS Code Webview instance (provides `cspSource` for the extension origin)
 * @param nonce   - A per-request nonce generated by {@link getNonce}
 * @returns A full `<meta http-equiv="Content-Security-Policy" ...>` HTML element string
 */
export function buildCspMeta(webview: vscode.Webview, nonce: string): string {
	const csp = [
		`default-src 'none'`,
		`img-src ${webview.cspSource} https: data:`,
		`style-src 'unsafe-inline' ${webview.cspSource}`,
		`font-src ${webview.cspSource} https: data:`,
		`script-src 'nonce-${nonce}'`,
	].join('; ');
	return `<meta http-equiv="Content-Security-Policy" content="${csp}" />`;
}

/**
 * Builds the `<link>` tag that loads the codicon font stylesheet (`@vscode/codicons`) into a
 * webview, so `<span class="codicon codicon-*"></span>` icons render correctly.
 *
 * The stylesheet + font file are copied to `dist/webview/codicons/` by esbuild.js. The `id`
 * matches the id `@vscode-elements/elements`' own `<vscode-icon>` component looks for
 * (`vscode-codicon-stylesheet`), so this single link also covers any vscode-elements icons.
 * The webview's existing CSP (`style-src`/`font-src` allow `webview.cspSource`) already permits
 * loading this stylesheet and its `@font-face` font from the extension's own resource root.
 *
 * @param webview - The VS Code Webview instance (used to resolve a loadable resource URI)
 * @param extensionUri - The extension's root Uri (provides the base path to `dist/webview`)
 * @returns A `<link rel="stylesheet">` HTML element string
 */
export function getCodiconStylesheetTag(webview: vscode.Webview, extensionUri: vscode.Uri): string {
	const href = webview.asWebviewUri(
		vscode.Uri.joinPath(extensionUri, 'dist', 'webview', 'codicons', 'codicon.css')
	);
	return `<link id="vscode-codicon-stylesheet" rel="stylesheet" href="${href}" />`;
}
